import re
from typing import Dict, Any, List

class FactualityGuardrailException(Exception):
    pass

def assert_no_hallucinations(response: Dict[str, Any], kpi_data: List[Dict[str, Any]]) -> bool:
    """
    Parses numbers generated by the LLM and asserts they are either default values
    or explicitly present in the provided KPI SQLite data payload to prevent hallucination.
    """
    summary = response.get("summary", "")
    actions = " ".join(response.get("actions", []))
    drivers = " ".join(response.get("drivers", []))
    
    combined_text = summary + " " + actions + " " + drivers
    
    # Extract all numbers from the LLM response
    llm_numbers = set(re.findall(r'\b\d+(?:\.\d+)?\b', combined_text))
    
    # Exclude basic linguistic numbers and small integers often used generally
    allowed_defaults = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "100", "50"}
    llm_numbers = llm_numbers - allowed_defaults
    
    if not llm_numbers:
        return True # No complex numbers to verify
        
    # Extract all numbers from the KPI payload
    kpi_numbers = set()
    for row in kpi_data:
        for val in row.values():
            if isinstance(val, (int, float)):
                kpi_numbers.add(str(val))
                if isinstance(val, float):
                    kpi_numbers.add(f"{val:.1f}")
                    kpi_numbers.add(f"{val:.2f}")
    
    # Verify that all complex LLM numbers exist in the source data
    for num in llm_numbers:
        if num not in kpi_numbers:
            # We detected a hallucinated number that doesn't exist in the KPI response
            raise FactualityGuardrailException(f"Hallucination detected: Number '{num}' generated by LLM is not present in the original KPI data source.")
            
    return True
